### ISSUE TITLE
Ticket Screen - Pull logic into hooks (cash calc, weight calc, etc)

### ISSUE THREAD

**Issue by ericwilhite** [TAC-Insight/fw-scale-frontend#153]

**Comment by ericwilhite** [comment]
@TAC-Insight/frontend 

This one should probably be broken up.

This screen is complex and these hooks will likely be substantial so I'd rather each of them be an isolated PR to review.

They can probably all live in a single file though: /hooks/laneRouteHooks.ts

**Comment by sspoon865** [comment]
List of hooks:

- [ ] Cash calculations
- [ ] Weight/scale calculations
- [ ] validateTruckTare
- [ ] laneFormState

Any others? 😎
