### ISSUE TITLE
remove hardcoded portal token for Eric

### ISSUE THREAD

**Issue by HaleyBoles** [TAC-Insight/fw-scale-frontend#176]

**Comment by ericwilhite** [comment]
I think I already did this

**Comment by ericwilhite** [comment]
I removed it in favor of just matching usernames with the existing web portal usernames.

Meaning anyone with a new user account can technically get it working if they have a matching old user account setup for a single tenant on the web portal

**Comment by HaleyBoles** [comment]
Oh sweet. I just had it in to-do as not an issue so figured would push it to issue.
