### ISSUE TITLE
Optional/Required PO Issue When Ticketing Inbound Orders

### ISSUE THREAD

**Issue by CoreyStaff** [TAC-Insight/fw-scale-frontend#240]
### Describe the bug
When ticketing on an order that has Ticket PO Rule set to Optional or Required on Inbound orders PO number does not populate when finalizing ticket. You have to click the ticket a second time to get the PO number to populate on the pre-finalized ticket.

### To Reproduce
1. Go to the Lane you'll be ticketing on.
2. Select your Truck, Customer, Order  that is Inbound and w/Ticket PO Rule set to Required, and Product.
3. Enter the PO number and Gross weight and click **+ Create Pending**
4. Click on the Pending ticket on the right hand side of the screen
5. Note the PO number has not populated
6. Enter the Tare and click **Finalize Ticket**
7. "Missing PO Number!"
8. Click Pending ticket on right hand side again
9. PO Number populates 

### Expected behavior
After clicking the Pending ticket the PO number should populate to allow the ticket to be finalized.

### Additional context
This issue poses complications mostly for Required Ticket PO Rules, but for Optional user would be able to Finalize Ticket with no issue other than noticing the PO Number didn't populate after the first click. Additionally, it appears the PO number will populate in the Web Portal regardless of PO being entered both times on an Optional Rule order.

**Comment by ericwilhite** [comment]
reproduced

@sspoon865 is going to take a look
