### ISSUE TITLE
"The field `utcOffset` does not exist on the type" error when selecting Orders from Orders menu.

### ISSUE THREAD

**Issue by devinTAC** [TAC-Insight/fw-scale-frontend#250]
**Describe the bug**
When selecting an order from the Orders menu, I am prompted with the error below. Attempted to select multiple orders that I created and orders that have been available prior. Products can be viewed and clicked on without issue. Error only prompts when selecting an Order.

In attempting to replicate/resolve: 
    -Logged out of FW across all browser windows.
    -Click into Orders
    -Error prompted.
In one instance, the Tenant Switcher broke in the Web Portal. Logout/login resolved.

**To Reproduce**
1. Click Orders
2. Click any Order
3. See error

Error:
 > The field `utcOffset` does not exist on the type `PortalTokenResponse`.: {"response":{"errors":[{"message":"The field `utcOffset` does not exist on the type `PortalTokenResponse`.","locations":[{"line":5,"column":7}],"path":["portalToken","portalTokenResponse"],"extensions":{"type":"PortalTokenResponse","field":"utcOffset","responseName":"utcOffset","specifiedBy":"http://spec.graphql.org/October2021/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types"}}],"status":400,"headers":{"map":{"access-control-allow-credentials":"true","access-control-allow-origin":"http://localhost:5001","content-type":"application/graphql-response+json; charset=utf-8","date":"Mon, 25 Sep 2023 18:06:05 GMT","server":"Kestrel","transfer-encoding":"chunked","vary":"Origin"}}},"request":{"query":"mutation PORTAL_TOKEN($input: PortalTokenInput!) {\n  portalToken(input: $input) {\n    portalTokenResponse {\n      portalToken\n      utcOffset\n      response {\n        returnCode\n        success\n        message\n        json\n      }\n    }\n    errors {\n      __typename\n      ... on Error {\n        message\n      }\n      ... on TacServerError {\n        code\n        message\n        serverMessage\n      }\n    }\n  }\n}","variables":{"input":{"username":"dlowetest"}}}} 
 
 
**Expected behavior**
The Orders page to load in the Web Portal.

**Screenshots**
Error:
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/146021527/ad9420f7-9cb3-47d1-8b6b-2cec74065800)

Broken Tenant Switcher:
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/146021527/5252771f-e58f-44ca-9af2-0a02bfd9a342)
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/146021527/91454e49-bf69-42bf-965e-3422c01f29a7)

**Additional context**
Fast-Weigh:
    -UI ver: 0.1.24
    -Server ver: 0.1.47
    -Web Portal: SSO Login - FWDev
    -App Login: dlowetest
    
    ***Error prompts when clicking "Payment" tab, Web Portal fails to load as well.

Firefox:
    -Version 117.0.1 (64-bit) - Up to date

**Comment by ericwilhite** [comment]
i _think_ this has been fixed and pushed live in the latest server and UI versions. Update to latest and reopen if still an issue.
