### ISSUE TITLE
Lane Route & Ticket History - Replace printJS with reprintTicket mutation

### ISSUE THREAD

**Issue by devinTAC** [TAC-Insight/fw-scale-frontend#251]
**Describe the bug**
After creating a new ticket, I am able to view the PDF when clicking PDF, but I am unable to view the print preview when selecting Print.

Could be due to not having a printer available/installed, but selecting any destination to Save to PDF, Microsoft Print to PDF, or OneNote does not provide preview.

Attempted to Replicate/Resolve:
Created new ticket in a different lane on the same order - Same result.
Created new ticket, used new truck/hauler, new customer, new order. - Same result

**To Reproduce**
1. Go to History
2. Click on Ticket
3. Select Print

**Expected behavior**
Visible Print Preview

**Screenshots**
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/146021527/e8659185-9799-4731-8695-9526e2f9f409)

**Additional context**
Fast-Weigh:
-UI ver: 0.1.24
-Server ver: 0.1.47
-Web Portal: SSO Login - FWDev
-App Login: dlowetest

Firefox:
-Version 117.0.1 (64-bit) - Up to date

**Comment by sspoon865** [comment]
This is a known issue in FireFox with the printJS library. We may need to research some alternatives or implement some User Agent-based checks for Mozilla/FireFox and handle printing differently in those cases.

**Comment by devinTAC** [comment]
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/146021527/5ab324fe-7d88-4def-8111-5d9fe33b8bae)

I tried to _break_ the ticket entry by adding as many products to one order as I could and noticed that it only created a PDF ticket for the first order, and killed the rest.

![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/146021527/57812c06-8e1c-4a49-b802-c4fdf835f87a)

**Comment by HaleyBoles** [comment]
> I tried to _break_ the ticket entry by adding as many products to one order as I could and noticed that it only created a PDF ticket for the first order, and killed the rest.

Split this to a new issue, unrelated to printing

**Comment by HaleyBoles** [comment]
@devinTAC Can you send over screenshot of what the print preview looks like on your end? 
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/128633188/7798bd0e-1d7e-4031-8bb9-dc1ec18d3584)
(My error is unrelated lol)

**Comment by devinTAC** [comment]
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/146021527/c91cba1a-238f-47e0-9ffb-83212dc1effe)
I actually don't have an error presented. I don't have a printer setup on this computer, so it might be related.

**Comment by HaleyBoles** [comment]
Thank you!

**Comment by HaleyBoles** [comment]
Will have reprintTicket mutation in the future we can use to replace printJS
