### ISSUE TITLE
Create and Pay Ticket Inbound/Outbound for Check/Credit Card

### ISSUE THREAD

**Issue by CoreyStaff** [TAC-Insight/fw-scale-frontend#253]
### Describe the bug
When ticketing on both Inbound and Outbound orders, the option to "Create and Pay" does not appear to function properly on orders utilizing Check or Credit Card as their pay types. 

For Outbound orders when entering the Gross weight it does the calculation for the Net weight and dollar amount, and when you click "Create and Pay Ticket" you are redirected to the "New Payment" screen in the web portal. However, for Check and Credit Card payment types the "Amount" is reflecting $0. 

For Inbound orders when entering the Gross Weight the Net weight and dollar amount are **not** calculated, and when you click "Create and Pay Ticket" you are redirected to the "New Payment" screen in the web portal. For all three; Cash, Check, and Credit Card payment types the "Amount" reflects $0. 

### To Reproduce
Steps to reproduce the Outbound behavior:
1. Fill out a ticket for an Outbound order with Credit/Check pay type
2. Click "Create and Pay Ticket"
3. Observe $0 "Amount"

Steps to reproduce the Inbound behavior:
1. Fill out a ticket for an Inbound order with Cash/Credit/Check pay type
2. Click "Create and Pay Ticket"
3. Observe $0 "Amount"

### Expected behavior
For both Outbound and Inbound orders, when clicking "Create and Pay Ticket" user should be redirected to "New Payment" in the web portal with correct dollar amount to be paid. 

### Screenshots
![image](https://github.com/TAC-Insight/fw-scale-frontend/assets/145610339/e32db10d-ec53-443b-af7f-fb6490078469)

### Additional context
The "No saved tare!" shows for both Inbound and Outbound orders.
UI Version: 0.1.25
Server Version: 0.1.51

**Comment by HaleyBoles** [comment]
Looks like those pay types are not getting pre-calculated pricing when synced to portal, causing the $0 amount on new payment screen

![Image](https://github.com/TAC-Insight/fw-scale-frontend/assets/128633188/26cf3517-cc12-42f3-b63c-ddc9462e12a3)

**Comment by HaleyBoles** [comment]
https://github.com/TAC-Insight/fw-scale-backend/releases/tag/V0.1.56
Fixed on newest server V
