### ISSUE TITLE
useTareOnInbound not applying to new trucks created in app

### ISSUE THREAD

**Issue by sspoon865** [TAC-Insight/fw-scale-frontend#275]
`useTareOnInbound` flag (on a truck's Hauler) is not applying correctly when ticketing using a truck that was entered through the app, but will work as expected when the truck is added through the web portal.

**Comment by HaleyBoles** [comment]
truck doesn't have the useTareOnInbound field and uses what is set on hauler record, so not sure what is going on here? May need to get with Chris on it
