### ISSUE TITLE
Merge Truck Add/Edit

### ISSUE THREAD

**Issue by ericwilhite** [TAC-Insight/fw-scale-frontend#93]
Are there meaningful differences that these screens should be separated? Or can they be merged like Order Add/Edit?
@HaleyBoles

**Comment by HaleyBoles** [comment]
> Are there meaningful differences that these screens should be separated? Or can they be merged like Order Add/Edit? @HaleyBoles

Not really many differences between the two, I think we would be able to merge them like Order with little issue

**Comment by HaleyBoles** [comment]
Already have a project to-do for it 😄

**Comment by HaleyBoles** [comment]
closing as duplicate of 
https://github.com/TAC-Insight/fw-scale-frontend/issues/95
